### ISSUE TITLE
Stuck on "Loading Sessions," can't use the scheduler!

### ISSUE THREAD

**Issue by Dragocaust** [Schemetrical/UBCScheduler#16]

**Comment by Schemetrical** [comment]
Which course?

**Comment by Dragocaust** [comment]
[image: image.png]

It's just stuck like this no matter what course I chose or how long I wait.

**Comment by Schemetrical** [comment]
I'll give it a look tonight. Thanks. Meanwhile take a look at ubcscheduler.github.io (made by a friend)

**Comment by Dragocaust** [comment]
Ok thank you!

**Comment by Schemetrical** [comment]
This should be fixed now! Go ahead and give it a shot, please reopen if this is still an issue. Thanks for letting me know.
